"""
Autonomous-generated image generation service.
Model: stabilityai/sd-turbo
Generated by: AI Self-Development System
"""

import asyncio
import io
from typing import Optional
from pathlib import Path

try:
    from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
    import torch
    from PIL import Image
    from huggingface_hub import login
    import os
    HAS_DIFFUSERS = True
except ImportError as e:
    HAS_DIFFUSERS = False
    IMPORT_ERROR = str(e)


class ImageGenerationService:
    """Service for generating images from text prompts."""

    def __init__(self):
        self.pipeline = None
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model_id = "stabilityai/sd-turbo"
        self.is_turbo = True
        
        # Authenticate with Hugging Face if token is available
        hf_token = os.getenv("HF_TOKEN")
        if hf_token:
            try:
                login(token=hf_token)
                print("✓ Authenticated with Hugging Face")
            except Exception as e:
                print(f"Warning: HF authentication failed: {e}")

    async def load_pipeline(self) -> bool:
        """Load the image generation model."""
        if not HAS_DIFFUSERS:
            return False
        
        if self.pipeline is not None:
            return True
        
        try:
            dtype = torch.float16 if self.device == "cuda" else torch.float32
            self.pipeline = StableDiffusionPipeline.from_pretrained(
                self.model_id,
                torch_dtype=dtype,
            )
            
            # Use DPM solver for faster inference
            if not self.is_turbo:
                self.pipeline.scheduler = DPMSolverMultistepScheduler.from_config(
                    self.pipeline.scheduler.config
                )
            
            if self.device == "cuda":
                self.pipeline = self.pipeline.to(self.device)
            
            return True
        except Exception as e:
            print(f"Error loading pipeline: {e}")
            return False

    async def generate_image(
        self,
        prompt: str,
        negative_prompt: str = "ugly, blurry, low quality, distorted",
        width: int = 512,
        height: int = 512,
        num_inference_steps: int = 1,
        guidance_scale: float = 0.0,
    ) -> Optional[Image.Image]:
        """Generate an image from a text prompt."""
        if not await self.load_pipeline():
            return None
        
        try:
            loop = asyncio.get_event_loop()
            
            def _generate():
                return self.pipeline(
                    prompt=prompt,
                    negative_prompt=negative_prompt,
                    width=width,
                    height=height,
                    num_inference_steps=num_inference_steps,
                    guidance_scale=guidance_scale,
                ).images[0]
            
            image = await loop.run_in_executor(None, _generate)
            return image
        except Exception as e:
            print(f"Error generating image: {e}")
            return None

    async def generate_image_bytes(
        self,
        prompt: str,
        width: int = 512,
        height: int = 512,
    ) -> Optional[bytes]:
        """Generate image and return as PNG bytes."""
        image = await self.generate_image(prompt, width=width, height=height)
        if image is None:
            return None
        
        buffer = io.BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()


# Global instance
_service: Optional[ImageGenerationService] = None


async def get_image_service() -> ImageGenerationService:
    """Get or create the image generation service."""
    global _service
    if _service is None:
        _service = ImageGenerationService()
    return _service


async def generate_image(
    prompt: str,
    width: int = 512,
    height: int = 512,
) -> Optional[Image.Image]:
    """Convenience function to generate an image."""
    service = await get_image_service()
    return await service.generate_image(prompt, width=width, height=height)
