"""
Image generation API endpoints.
Auto-generated by AI Self-Development System
"""

import base64
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from backend.app.services.image_generation import generate_image


router = APIRouter(prefix="/api/images", tags=["images"])


class ImageGenerationRequest(BaseModel):
    prompt: str
    negative_prompt: str = ""
    width: int = 512
    height: int = 512
    num_steps: int = 28


class ImageGenerationResponse(BaseModel):
    status: str
    message: str
    image_base64: str | None = None
    width: int | None = None
    height: int | None = None


@router.post("/generate", response_model=ImageGenerationResponse)
async def generate_image_endpoint(request: ImageGenerationRequest):
    """Generate an image from a text prompt."""
    try:
        image = await generate_image(
            prompt=request.prompt,
            negative_prompt=request.negative_prompt,
            width=request.width,
            height=request.height,
            num_inference_steps=request.num_steps,
        )
        
        if image is None:
            raise HTTPException(status_code=500, detail="Failed to generate image")
        
        # Convert to base64
        import io
        buffer = io.BytesIO()
        image.save(buffer, format="PNG")
        image_base64 = base64.b64encode(buffer.getvalue()).decode("utf-8")
        
        return ImageGenerationResponse(
            status="success",
            message=f"Image generated from prompt: {request.prompt}",
            image_base64=image_base64,
            width=image.width,
            height=image.height,
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
