/**
 * Console Message Utility
 * Task: how to write console.log in python ?
 * Generated by ISE AI Autonomous Agent
 */

// Log the message to browser console
console.log("Hello World");

// Export for reuse
export function logMessage(msg = "Hello World") {
    console.log(msg);
}

export function logWithTimestamp(msg = "Hello World") {
    const timestamp = new Date().toISOString();
    console.log(`[${timestamp}] ${msg}`);
}

// Auto-execute on import
console.log("✅ Console message utility loaded");
