/**
 * Browser Console Logger
 * Generated by ISE AI Autonomous Coding Agent
 * 
 * This script logs messages to the browser console.
 * Open browser DevTools (F12) to see the output.
 */

// Log the message to browser console
console.log("Hello World");

// Also log additional info for debugging
console.log("🤖 ISE AI Agent - Console Log Test");
console.log("Timestamp:", new Date().toISOString());
console.log("User Agent:", navigator.userAgent);
console.log("Page URL:", window.location.href);

// Export function for reuse
export function logToConsole(msg) {
    console.log(msg);
}

export function logWithTimestamp(msg) {
    console.log(`[${new Date().toISOString()}] ${msg}`);
}

// Auto-execute on module load
console.log("✅ Console logger initialized");
